# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addstudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(236, 394)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../pyqt5/images/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form{\n"
"background-color: white;\n"
"}")
        self.header = QtWidgets.QWidget(Form)
        self.header.setGeometry(QtCore.QRect(0, 0, 240, 101))
        self.header.setStyleSheet("#header{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.header.setObjectName("header")
        self.checkBox = QtWidgets.QCheckBox(self.header)
        self.checkBox.setGeometry(QtCore.QRect(20, 10, 151, 17))
        self.checkBox.setObjectName("checkBox")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 150, 201, 186))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.studentIDLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.studentIDLabel.setObjectName("studentIDLabel")
        self.gridLayout.addWidget(self.studentIDLabel, 0, 0, 1, 1)
        self.studentIDLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.studentIDLineEdit.setObjectName("studentIDLineEdit")
        self.gridLayout.addWidget(self.studentIDLineEdit, 0, 1, 1, 1)
        self.firstNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.gridLayout.addWidget(self.firstNameLabel, 1, 0, 1, 1)
        self.firstNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.gridLayout.addWidget(self.firstNameLineEdit, 1, 1, 1, 1)
        self.middleNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.middleNameLabel.setObjectName("middleNameLabel")
        self.gridLayout.addWidget(self.middleNameLabel, 2, 0, 1, 1)
        self.middleNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.middleNameLineEdit.setObjectName("middleNameLineEdit")
        self.gridLayout.addWidget(self.middleNameLineEdit, 2, 1, 1, 1)
        self.lastNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.gridLayout.addWidget(self.lastNameLabel, 3, 0, 1, 1)
        self.lastNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.gridLayout.addWidget(self.lastNameLineEdit, 3, 1, 1, 1)
        self.courseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.courseLabel.setObjectName("courseLabel")
        self.gridLayout.addWidget(self.courseLabel, 4, 0, 1, 1)
        self.courseLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.courseLineEdit.setObjectName("courseLineEdit")
        self.gridLayout.addWidget(self.courseLineEdit, 4, 1, 1, 1)
        self.yearLevelLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yearLevelLabel.setObjectName("yearLevelLabel")
        self.gridLayout.addWidget(self.yearLevelLabel, 5, 0, 1, 1)
        self.yearLevelComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.yearLevelComboBox.setObjectName("yearLevelComboBox")
        self.yearLevelComboBox.addItems(['1','2','3','4','5'])
        self.gridLayout.addWidget(self.yearLevelComboBox, 5, 1, 1, 1)
        self.genderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.genderLabel.setObjectName("genderLabel")
        self.gridLayout.addWidget(self.genderLabel, 6, 0, 1, 1)
        self.genderComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItems(['Choose Gender', 'Male', 'Female', 'Lesbian', 'Gay', 'Bisexual', 'Transgender', 'Unknown'])
        self.gridLayout.addWidget(self.genderComboBox, 6, 1, 1, 1)
        self.label_pic = QtWidgets.QLabel(Form)
        self.label_pic.setGeometry(QtCore.QRect(70, 40, 101, 100))
        self.label_pic.setText("")
        self.label_pic.setPixmap(QtGui.QPixmap("../../pyqt5/images/changeusername_icon.png"))
        self.label_pic.setScaledContents(True)
        self.label_pic.setWordWrap(False)
        self.label_pic.setObjectName("label_pic")
        self.pushButton_editPic = QtWidgets.QPushButton(Form)
        self.pushButton_editPic.setGeometry(QtCore.QRect(170, 110, 31, 23))
        self.pushButton_editPic.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../pyqt5/images/edit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_editPic.setIcon(icon1)
        self.pushButton_editPic.setFlat(True)
        self.pushButton_editPic.setObjectName("pushButton_editPic")
        self.pushButton_AddStudent = QtWidgets.QPushButton(Form)
        self.pushButton_AddStudent.setGeometry(QtCore.QRect(20, 350, 201, 23))
        self.pushButton_AddStudent.setObjectName("pushButton_AddStudent")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add New"))
        self.checkBox.setText(_translate("Form", "Do not close automatically"))
        self.studentIDLabel.setText(_translate("Form", "studentID"))
        self.firstNameLabel.setText(_translate("Form", "First Name"))
        self.middleNameLabel.setText(_translate("Form", "Middle Name"))
        self.lastNameLabel.setText(_translate("Form", "Last Name"))
        self.courseLabel.setText(_translate("Form", "Course"))
        self.yearLevelLabel.setText(_translate("Form", "Year Level"))
        self.genderLabel.setText(_translate("Form", "Gender"))
        self.pushButton_AddStudent.setText(_translate("Form", "Add Student"))
