# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'courseForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_courseForm(object):
    def setupUi(self, MainWindow, parent=None, mode=None, course_code=None, winName=None):
        self.p = parent
        self.mode = mode
        self.coursecode = course_code
        self.winName = winName
        MainWindow.setObjectName(self.winName)
        MainWindow.setFixedSize(335, 217)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 341, 51))
        self.header.setStyleSheet("#header{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.header.setObjectName("header")
        self.label = QtWidgets.QLabel(self.header)
        self.label.setGeometry(QtCore.QRect(0, 0, 331, 20))
        self.label.setStyleSheet("#label{\n"
"color: white;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.coursecode = QtWidgets.QLabel(self.header)
        self.coursecode.setGeometry(QtCore.QRect(0, 20, 331, 20))
        self.coursecode.setStyleSheet("#coursecode{\n"
"color: white;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.coursecode.setAlignment(QtCore.Qt.AlignCenter)
        self.coursecode.setObjectName("coursecode")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 331, 20))
        self.label_3.setStyleSheet("#label{\n"
"color: white;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 90, 315, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 140, 221, 41))
        self.pushButton.setStyleSheet("#pushButton{\n"
"color: white;\n"
"background-color: rgb(0, 170, 255);\n"
"border: 1px solid rgb(0, 170, 255);\n"
"border-radius: 20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Course"))
        self.label.setText(_translate("MainWindow", "course code:"))
        self.coursecode.setText(_translate("MainWindow", "CCODE"))
        self.label_3.setText(_translate("MainWindow", "Course Name"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
