# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, MainWindow, parent=None):
        self.p = parent
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(264, 344)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 271, 401))
        self.header.setStyleSheet("#header{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.header.setObjectName("header")
        self.labelID = QtWidgets.QLabel(self.header)
        self.labelID.setGeometry(QtCore.QRect(20, 55, 71, 16))
        self.labelID.setObjectName("labelID")
        self.lineEdit = QtWidgets.QLineEdit(self.header)
        self.lineEdit.setGeometry(QtCore.QRect(100, 50, 151, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.labelfirstname = QtWidgets.QLabel(self.header)
        self.labelfirstname.setGeometry(QtCore.QRect(20, 85, 71, 16))
        self.labelfirstname.setObjectName("labelfirstname")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.header)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 80, 151, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.labelmiddlename = QtWidgets.QLabel(self.header)
        self.labelmiddlename.setGeometry(QtCore.QRect(20, 115, 71, 16))
        self.labelmiddlename.setObjectName("labelmiddlename")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.header)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 110, 151, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.labelcourse = QtWidgets.QLabel(self.header)
        self.labelcourse.setGeometry(QtCore.QRect(20, 175, 71, 16))
        self.labelcourse.setObjectName("labelcourse")
        self.labellastname = QtWidgets.QLabel(self.header)
        self.labellastname.setGeometry(QtCore.QRect(20, 145, 71, 16))
        self.labellastname.setObjectName("labellastname")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.header)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 140, 151, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.labelyearlevel = QtWidgets.QLabel(self.header)
        self.labelyearlevel.setGeometry(QtCore.QRect(20, 205, 71, 16))
        self.labelyearlevel.setObjectName("labelyearlevel")
        self.labelgender = QtWidgets.QLabel(self.header)
        self.labelgender.setGeometry(QtCore.QRect(20, 235, 71, 16))
        self.labelgender.setObjectName("labelgender")
        self.comboBox = QtWidgets.QComboBox(self.header)
        self.comboBox.setGeometry(QtCore.QRect(100, 170, 151, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.header)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 200, 151, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.header)
        self.comboBox_3.setGeometry(QtCore.QRect(100, 230, 151, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton = QtWidgets.QPushButton(self.header)
        self.pushButton.setGeometry(QtCore.QRect(20, 270, 231, 41))
        self.pushButton.setStyleSheet("#pushButton{\n"
"broder: 1px solid white;\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Student"))
        self.labelID.setText(_translate("MainWindow", "STUDENT ID"))
        self.labelfirstname.setText(_translate("MainWindow", "FIRST NAME"))
        self.labelmiddlename.setText(_translate("MainWindow", "MIDDLE NAME"))
        self.labelcourse.setText(_translate("MainWindow", "COURSE"))
        self.labellastname.setText(_translate("MainWindow", "LAST NAME"))
        self.labelyearlevel.setText(_translate("MainWindow", "YEAR LEVEL"))
        self.labelgender.setText(_translate("MainWindow", "GENDER"))
        self.pushButton.setText(_translate("MainWindow", "Add Student"))
