from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(236, 359)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.header = QtWidgets.QWidget(Form)
        self.header.setGeometry(QtCore.QRect(0, 0, 240, 61))
        self.header.setStyleSheet("#header{\n"
"background-color: rgb(0, 170, 255);\n"
"}")
        self.header.setObjectName("header")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 130, 201, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.studentIDLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.studentIDLabel.setObjectName("studentIDLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.studentIDLabel)
        self.studentIDLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.studentIDLineEdit.setObjectName("studentIDLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.studentIDLineEdit)
        self.firstNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.firstNameLabel)
        self.firstNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.firstNameLineEdit)
        self.middleNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.middleNameLabel.setObjectName("middleNameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.middleNameLabel)
        self.middleNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.middleNameLineEdit.setObjectName("middleNameLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.middleNameLineEdit)
        self.lastNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lastNameLineEdit)
        self.courseLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.courseLabel.setObjectName("courseLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.courseLabel)
        self.courseLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.courseLineEdit.setObjectName("courseLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.courseLineEdit)
        self.yearLevelLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yearLevelLabel.setObjectName("yearLevelLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.yearLevelLabel)
        self.yearLevelComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.yearLevelComboBox.setObjectName("yearLevelComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.yearLevelComboBox)
        self.genderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.genderComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.genderComboBox.setObjectName("genderComboBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.genderComboBox)
        self.AddStudent = QtWidgets.QPushButton(self.formLayoutWidget)
        self.AddStudent.setObjectName("AddStudent")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.AddStudent)
        self.label_pic = QtWidgets.QLabel(Form)
        self.label_pic.setGeometry(QtCore.QRect(70, 20, 101, 100))
        self.label_pic.setText("")
        self.label_pic.setPixmap(QtGui.QPixmap("images/changeusername_icon.png"))
        self.label_pic.setScaledContents(True)
        self.label_pic.setWordWrap(False)
        self.label_pic.setObjectName("label_pic")
        self.pushButton_editPic = QtWidgets.QPushButton(Form)
        self.pushButton_editPic.setGeometry(QtCore.QRect(170, 90, 31, 23))
        self.pushButton_editPic.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/edit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_editPic.setIcon(icon1)
        self.pushButton_editPic.setFlat(True)
        self.pushButton_editPic.setObjectName("pushButton_editPic")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add New"))
        self.studentIDLabel.setText(_translate("Form", "studentID"))
        self.firstNameLabel.setText(_translate("Form", "First Name"))
        self.middleNameLabel.setText(_translate("Form", "Middle Name"))
        self.lastNameLabel.setText(_translate("Form", "Last Name"))
        self.courseLabel.setText(_translate("Form", "Course"))
        self.yearLevelLabel.setText(_translate("Form", "Year Level"))
        self.genderLabel.setText(_translate("Form", "Gender"))
        self.AddStudent.setText(_translate("Form", "Add Student"))
