# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(805, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form {\n"
"background-color: #daecf4;\n"
"}")
        self.label_SSIS = QtWidgets.QLabel(Form)
        self.label_SSIS.setGeometry(QtCore.QRect(30, 150, 461, 261))
        self.label_SSIS.setText("")
        self.label_SSIS.setPixmap(QtGui.QPixmap("images/login_text.png"))
        self.label_SSIS.setScaledContents(True)
        self.label_SSIS.setObjectName("label_SSIS")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, -30, 521, 501))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 70, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 70, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 70, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 70, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/login-template.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_username = QtWidgets.QLabel(Form)
        self.label_username.setGeometry(QtCore.QRect(410, 200, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_username.setFont(font)
        self.label_username.setStyleSheet("#label_username{\n"
"color: #128785;\n"
"}")
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(Form)
        self.label_password.setGeometry(QtCore.QRect(410, 240, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("#label_password{\n"
"color: #128785;\n"
"}")
        self.label_password.setObjectName("label_password")
        self.line1 = QtWidgets.QFrame(Form)
        self.line1.setGeometry(QtCore.QRect(510, 210, 191, 16))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QFrame(Form)
        self.line2.setGeometry(QtCore.QRect(510, 249, 191, 16))
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.pushButton_login = QtWidgets.QPushButton(Form)
        self.pushButton_login.setGeometry(QtCore.QRect(510, 290, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_login.setStyleSheet("#pushButton_login{\n"
"color: white;\n"
"background-color: #0a9cad;\n"
"border: 1px white;\n"
"border-radius: 20px;\n"
"}")
        self.pushButton_login.setFlat(False)
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_signup = QtWidgets.QPushButton(Form)
        self.pushButton_signup.setGeometry(QtCore.QRect(510, 365, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_signup.setFont(font)
        self.pushButton_signup.setStyleSheet("#pushButton_signup{\n"
"color: black;\n"
"background-color: white;\n"
"border: 1px solid #0a9cad;\n"
"border-radius: 20px;\n"
"}")
        self.pushButton_signup.setFlat(False)
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.pushButton_signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(580, 340, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_username = QtWidgets.QLineEdit(Form)
        self.lineEdit_username.setGeometry(QtCore.QRect(510, 190, 191, 25))
        self.lineEdit_username.setStyleSheet("#lineEdit_username{\n"
"border: 0px;\n"
"}")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(510, 229, 191, 25))
        self.lineEdit_password.setStyleSheet("#lineEdit_password{\n"
"border: 0px;\n"
"}")
        self.lineEdit_password.setObjectName("lineEdit_password")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "[SSIS] Login"))
        self.label_username.setText(_translate("Form", "USERNAME:"))
        self.label_password.setText(_translate("Form", "PASSWORD:"))
        self.pushButton_login.setText(_translate("Form", "Log In"))
        self.pushButton_signup.setText(_translate("Form", "Sign Up"))
        self.label.setText(_translate("Form", "or"))
